I'm sorry, but an uncaught exception occurred.

After loading the script.
WindowsError: [Error 32] The process cannot access the file because it is being used by another process

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/bootstrap.py", line 326, in bootstrap
    renpy.main.main()
  File "renpy/main.py", line 505, in main
    if renpy.parser.report_parse_errors():
  File "renpy/parser.py", line 2962, in report_parse_errors
    renpy.display.error.report_parse_errors(full_text, error_fn)
  File "renpy/display/error.py", line 172, in report_parse_errors
    error_dump()
  File "renpy/display/error.py", line 84, in error_dump
    renpy.dump.dump(True)
  File "renpy/dump.py", line 260, in dump
    os.rename(new, filename)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process

Windows-10-10.0.19041
Ren'Py 7.4.4.1439
12_prototype 1.1
Fri May 28 16:16:32 2021
